# Generated by Django 3.0 on 2023-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.IntegerField()),
                ('comment', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
